# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdcGDAvbVTmn9zNog7nfgi5k9NXrvcRi
"""

import steamlit as st
import random

st.title('Test Streamlit')
st.write('Hello Wold!')

if st.button('Generate Random Number'):
    random_number = random.randin(1,100)
    st.write(f'Random Number: {ramdom_number}')
